### ISSUE TITLE
Problem of setup a private swap   network

### ISSUE THREAD

**Issue by jsp2012** [kozyilmaz/bether#1]
when  I run the command:echo -ne '\n' | swarm --bzzaccount $BZZKEY --datadir "~/bether" --ens-api "/root/bether/geth.ipc" --bzznetworkid 666 &
there was a error:Fatal: Can't find swarm account key: no key for given address or file
please tell me how to solve it.  thank you.

**Comment by kozyilmaz** [comment]
Hi @jsp2012 , swarm needs a valid wallet address as `BZZKEY` created on the node. Can you create a wallet address and export it as `BZZKEY` first:
```javascript
$ export BZZKEY=ffecc801c6eed3fbc45d69e3e12ad4d9660f0d30
```

**Comment by jsp2012** [comment]
I follow your export BZZKEY. need I create a wallt adress by myself?could you tell me how to create?

**Comment by kozyilmaz** [comment]
Yes, you need to have your own wallet address. I assume you already launched `geth`before `swarm` like below (as an example):
```javascript
$ geth --rpc --rpcport "8000" --rpccorsdomain "*" --datadir "~/bether" --port "30303" --nodiscover --rpcapi "db,eth,net,web3" --identity "mbp-linux" --networkid 666 console
```
If you have a command line prompt on `geth`, you may type command below to list your wallet addresses.
```javascript
> eth.accounts
```
You may use one of those as `BZZKEY`

If you do not have `geth` console, you may run a command to query wallet address (for example):
```javascript
$ geth --rpc --rpcport "8000" --rpccorsdomain "*" --datadir "~/bether" --port "30303" --nodiscover --rpcapi "db,eth,net,web3" --identity "mbp-linux" --networkid 666 account list
```
This command is very similar to the command that use to launch `geth`, just write "account list" instead of "console" at the end.

**Comment by jsp2012** [comment]
thanks.it worked. another question,I wonder if i can   only set one Ethereum network and one swarm network.

**Comment by kozyilmaz** [comment]
what do you mean by that, can you elaborate a bit? You don't have to run a swarm network to run a private Ethereum network.

**Comment by jsp2012** [comment]
sorry,I mean set Ethereum Network with one node。

**Comment by kozyilmaz** [comment]
I think you already did it, if you setup only one private node using this tutorial you already achieved it :)
https://github.com/kozyilmaz/bether/blob/master/readme/README.network.md

If you run this tutorial you may monitor that single node too
https://github.com/kozyilmaz/bether/blob/master/readme/README.monitor.md

I doubt a single private node will do any good but that's your call.

**Comment by jsp2012** [comment]
thank you.
